dist: trusty
sudo: false
language: generic
services:
  - docker
branches:
  only:
    - master
env:
  - SPELLCHECK=true
install:
  - source ci/install.sh
  - gem install danger-prose
  - gem install danger-commit_lint
  - gem install danger-welcome_message
  - pip install proselint
script:
  - bash build/build.sh
  - prose.disable_linters = ["misc.scare_quotes", "misc.tense_present"]
  - prose.lint_files
  - commit_lint.check
  - welcome_message.greet
cache:
  directories:
    - ci/cache
deploy:
  provider: script
  script: bash ci/deploy.sh
  skip_cleanup: true
  on:
    branch: master
    condition: $TRAVIS_EVENT_TYPE = "push" && (-v MANUBOT_SSH_PRIVATE_KEY || "${!encrypted_*}" != "")
